<?php
/**
 * TL_ROOT/system/modules/invoice_and_offer/languages/de/default.php
 *
 * Contao extension: invoice_and_offer
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao']['types']['offer']	= 'Angebot';
$GLOBALS['TL_LANG']['tl_iao']['types']['invoice']	= 'Rechnung';
$GLOBALS['TL_LANG']['tl_iao']['types']['credit']	= 'Gutschrift';

$GLOBALS['TL_LANG']['tl_iao']['active']	= array('aktiv', '');
$GLOBALS['TL_LANG']['tl_iao']['status']['title']	= array('Status', '');
$GLOBALS['TL_LANG']['tl_iao']['counter']	= array('Counter','');

$GLOBALS['TL_LANG']['tl_iao']['credit_status'][0]	= array('nicht angenommen', '');
$GLOBALS['TL_LANG']['tl_iao']['credit_status'][1]	= array('angenommen', '');

$GLOBALS['TL_LANG']['tl_iao']['gender']['male']	=  'Herr';
$GLOBALS['TL_LANG']['tl_iao']['gender']['female']	=  'Frau';

$GLOBALS['TL_LANG']['ERR']['PermissionDenied'] = 'keine Berechtigung für %s';
