<?php
/**
 * TL_ROOT/system/modules/invoice_and_offer/languages/de/modules.php
 *
 * Contao extension: invoice_and_offer
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Back end modules
 */
 $GLOBALS['TL_LANG']['MOD']['iao']  = 'Rechnungen & Angebote';
 $GLOBALS['TL_LANG']['MOD']['iao_offer']	= array('Angebote', 'Verwalten Sie hier Ihre Angebote.');
 $GLOBALS['TL_LANG']['MOD']['iao_invoice']	= array('Rechnungen', 'Verwalten Sie hier Ihre Rechnungen.');
 $GLOBALS['TL_LANG']['MOD']['iao_reminder']	= array('Rückstände', 'Verwalten Sie hier Ihre Rückstände.');
 $GLOBALS['TL_LANG']['MOD']['iao_credit']	= array('Gutschriften', 'Verwalten Sie hier Ihre Gutschriften.');
 $GLOBALS['TL_LANG']['MOD']['iao_templates']	= array('Vorlagen (Text)', 'Verwalten Sie die Vorlagen für die Standarttexte vor und nach den Posten von Rechnungen, Angebote und Gutschriften.');
 $GLOBALS['TL_LANG']['MOD']['iao_posten_templates']	= array('Vorlagen (Posten)', 'Verwalten Sie die Vorlagen für die Posten von Rechnungen, Angebote und Gutschriften.');
 $GLOBALS['TL_LANG']['MOD']['iao_customer']	= array('Kunden', 'Verwalten Sie ihre Kundendaten.');
 $GLOBALS['TL_LANG']['MOD']['iao_settings']	= array('Einstellungen', 'Verwalten Sie die allgemeinen Einstellungen zu den Angebote, Rechnungen und Gutschriften.');
