<?php
/**
 * TL_ROOT/system/modules/invoice_and_offer/languages/de/tl_iao_projects.php
 *
 * Contao extension: invoice_and_offer
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_projects']['setting_id']	=	array('Konfiguration','');
$GLOBALS['TL_LANG']['tl_iao_projects']['title']	=	array('Bezeichnung','Bezeichnung des Elementes');
$GLOBALS['TL_LANG']['tl_iao_projects']['member']	=	array('Kunde','Adresse aus gespeicherten Kunden in nachstehendes Feld befüllen');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_title']	=	array('Titel für die Referenzen','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_customer']	=	array('Kunden-Beschreibung','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_todo']	=	array('Aufgaben','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_desription']	=	array('Projekt-Beschreibung','');
$GLOBALS['TL_LANG']['tl_iao_projects']['in_reference']	=	array('in Referenzen aufnehmen.','');
$GLOBALS['TL_LANG']['tl_iao_projects']['finished']	=	array('fertig gestellt','');
$GLOBALS['TL_LANG']['tl_iao_projects']['singleSRC']	=	array('Projekt-Bild','wird für alle Projekt-Teaser als Hauptbild verwendet');
$GLOBALS['TL_LANG']['tl_iao_projects']['multiSRC']	=	array('Projekt-Bild-Galerie','');
$GLOBALS['TL_LANG']['tl_iao_projects']['url']	=	array('www','Website-URL');
$GLOBALS['TL_LANG']['tl_iao_projects']['notice']	=	array('Notiz','Diese Notizen werden ausschließlich im Backend verwendet.');

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_iao_projects']['offer']	=	array('Projekt-Angebote','alle Angebote von diesem Projekt');
$GLOBALS['TL_LANG']['tl_iao_projects']['invoice']	=	array('Projekt-Rechnungen','alle Rechnungen von diesem Projekt');
$GLOBALS['TL_LANG']['tl_iao_projects']['credit']	=	array('Neues Projekt','alle Gutschriften vone diesem Projekt');
$GLOBALS['TL_LANG']['tl_iao_projects']['reminder']	=	array('Neues Projekt','alle Erinnerungen von diesem Projekt');
$GLOBALS['TL_LANG']['tl_iao_projects']['new']	=	array('Neues Projekt','Ein neues Projekt anlegen');
$GLOBALS['TL_LANG']['tl_iao_projects']['edit']	=	array('Projekt bearbeiten','Projekt ID %s bearbeiten');
$GLOBALS['TL_LANG']['tl_iao_projects']['copy']	=	array('Projekt duplizieren','Projekt ID %s duplizieren');
$GLOBALS['TL_LANG']['tl_iao_projects']['delete']	=	array('Projekt löschen','Projekt ID %s löschen');
$GLOBALS['TL_LANG']['tl_iao_projects']['deleteConfirm']	=	'Soll das Projekt mit der ID %s wirklich gelöscht werden?!';
$GLOBALS['TL_LANG']['tl_iao_projects']['show']	=	array('Details anzeigen','Details vom Projekt ID %s anzeigen');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_iao_projects']['settings_legend']	=	'Konfiguration-Zuweisung';
$GLOBALS['TL_LANG']['tl_iao_projects']['project_legend']	=	'Projekt-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_legend']	=	'Referenz-Zuweisung';

/**
* Frontend-Templates
*/
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['title'] = 'Titel/ Rechnungsnr.:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['date'] = 'erstellt am:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['price'] = 'Betrag:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['remaining'] = 'offen:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['file'] = 'PDF:';


// Meldungen
$GLOBALS['TL_LANG']['tl_iao_projects']['no_entries_msg'] = 'Es sind keine Einträge für diesen Bereich vorhanden.';
