<?php
/**
 * TL_ROOT/system/modules/invoice_and_offer/languages/de/tl_iao_item_units.php
 *
 * Contao extension: invoice_and_offer
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_iao_item_units']['name'][0]              = 'Name des Einheites';
$GLOBALS['TL_LANG']['tl_iao_item_units']['name'][1]              = 'Geben Sie einen eindeutigen Namen ein.';
$GLOBALS['TL_LANG']['tl_iao_item_units']['value'][0]              = 'Wert';
$GLOBALS['TL_LANG']['tl_iao_item_units']['value'][1]              = 'Ist der Wert im selekt-Eintrag. In älteren Versionen wurde dies fest als englischer Wert angelegt (days,year,flaterate,piece,minutes)';
$GLOBALS['TL_LANG']['tl_iao_item_units']['singular'][0]          = 'Name als Einzahl';
$GLOBALS['TL_LANG']['tl_iao_item_units']['singular'][1]          = 'z.B. Stunde oder Tag';
$GLOBALS['TL_LANG']['tl_iao_item_units']['majority'][0]          = 'Name als Mehrzahl';
$GLOBALS['TL_LANG']['tl_iao_item_units']['majority'][1]          = 'z.B. Stunden oder Tage';
$GLOBALS['TL_LANG']['tl_iao_item_units']['sorting'][0]				= 'Sortierung';
$GLOBALS['TL_LANG']['tl_iao_item_units']['sorting'][1]             = 'Um die Sortierung anzupassen, tragen Sie hier eine Zahl ein.';



/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_iao_item_units']['new'][0]                          = 'Neue Einheit';
$GLOBALS['TL_LANG']['tl_iao_item_units']['new'][1]                          = 'Eine neue Einheit erstellen.';
$GLOBALS['TL_LANG']['tl_iao_item_units']['edit'][0]                         = 'Einheit bearbeiten';
$GLOBALS['TL_LANG']['tl_iao_item_units']['edit'][1]                         = 'Einheit ID %s bearbeiten.';
$GLOBALS['TL_LANG']['tl_iao_item_units']['copy'][0]                         = 'Einheit duplizieren';
$GLOBALS['TL_LANG']['tl_iao_item_units']['copy'][1]                         = 'Einheit ID %s duplizieren.';
$GLOBALS['TL_LANG']['tl_iao_item_units']['delete'][0]                       = 'Einheit löschen';
$GLOBALS['TL_LANG']['tl_iao_item_units']['delete'][1]                       = 'Einheit ID %s löschen.';
$GLOBALS['TL_LANG']['tl_iao_item_units']['show'][0]                         = 'Einheitsdetails anzeigen';
$GLOBALS['TL_LANG']['tl_iao_item_units']['show'][1]                         = 'Details für Einheit ID %s anzeigen.';

