<?php
/**
 * TL_ROOT/system/modules/myContaoSearchPortal/languages/de/tl_iao_settings.php 
 * 
 * TYPOlight extension: myContaoSearchPortal
 * Deutsch translation file 
 * 
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL 
 * Author    : Sven Rhinow, http://www.sr-tag.de/ 
 * Translator: Sven Rhinow (ScuM666) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Fields
 */               
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_sslorder']= array('SSL bei der Bestellung', 'Soll der Bestellvorgang über SSL abewickelt werden?');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_tax']= array('Standard-Steuersatz', 'Wird für die Berechnung der Standardwerte benötigt. Wirkt sich auch auf Verpackungskosten etc aus.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_costumer_group']= array('Kunden-Gruppe', 'Diese Gruppen werden automatisch bei fehlender Angabe der Firma gesetzt.'); 
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_currency']= array('Währungkürzel', 'Bitte das offizielle Währungskennzeichen dieses Shops eingeben.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_currencysymbol']= array('Währungssymbol', 'Bitte das Währungssymbol der Shopwährung.');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_pdf_margins']= array('Randabstände', 'Geben Sie hier die Abstände in folgender Reihenfolge ein. (oben,rechts,unten,links, Maßeinheit)');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_pdf_css']= array('CSS-Datei für die PDF-Darstellung', '');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_invoice_mail_from']= array('Rechnung-Absender-Mailadresse', 'in der form foo@bar.de');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_invoice_startnumber']= array('Rechnung-Startnummer', 'ab welcher Nummer soll hochgezählt werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_invoice_pdf']= array('Rechnung-PDF-Vorlage', 'eine PDF-Vorlage sollte 2 Seiten beinhalten die erste für die Startseite und die zweite für alle weiteren.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_invoice_number_format']= array('Rechnung-Nummer-Formatierung', 'die Platzhalter  {date} für aktuelles Datum  und {nr} für die Rechnungs-ID können angegeben werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_invoice_duration']= array('Begleichungsdauer', 'in Tagen');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_offer_mail_from']= array('Angebot-Absender-Mailadresse', 'in der form foo@bar.de');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_offer_startnumber']= array('Angebot-Startnummer', 'ab welcher Nummer soll hochgezählt werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_offer_pdf']= array('Angebot-PDF-Vorlage', 'eine PDF-Vorlage sollte 2 Seiten beinhalten die erste für die Startseite und die zweite für alle weiteren.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_offer_number_format']= array('Angebot-Nummer-Formatierung', 'die Platzhalter  {date} für aktuelles Datum  und {nr} für die Angebot-ID können angegeben werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_offer_expiry_date']= array('Angebot gültig bis', 'die Platzhalter  im Format d+n:m-n:Y+n für ein viertel Jahr z.B. d:m+3:Y.');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_credit_mail_from']= array('Gutschrift-Absender-Mailadresse', 'in der form foo@bar.de');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_credit_startnumber']= array('Gutschrift-Startnummer', 'ab welcher Nummer soll hochgezählt werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_credit_pdf']= array('Gutschrift-PDF-Vorlage', 'eine PDF-Vorlage sollte 2 Seiten beinhalten die erste für die Startseite und die zweite für alle weiteren.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_credit_number_format']= array('Gutschrift-Nummer-Formatierung', 'die Platzhalter  {date} für aktuelles Datum  und {nr} für die Gutschrift-ID können angegeben werden.');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_credit_expiry_date']= array('Gutschrift gültig bis', 'die Platzhalter  im Format d+n:m-n:Y+n für ein viertel Jahr z.B. d:m+3:Y.');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_memory_duration']= array('Erinnerungs-Zeitraum', '');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_memory_text']= array('Erinnerungs-Text', 'Platzhalter: Herr/Frau = ##gender## , Nachname = ##lastname## , Rechnungssumme = ##brutto## , Rechnungsdatum = ##invoice-date## , Rechnungsnummer = ##invoice-id-str##, Frist-Datum = ##period-date##');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_memory_pdf']= array('Erinnerungs-PDF-Vorlage', '');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_1_duration']= array('1. Mahnung-Zeitraum', '');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_1_text']= array('1. Mahnung-Text', 'Platzhalter: Herr/Frau = ##gender## , Nachname = ##lastname## , Rechnungssumme = ##brutto## , Rechnungsdatum = ##invoice-date## , Rechnungsnummer = ##invoice-id-str##, Frist-Datum = ##period-date##');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_1_pdf']= array('1. Mahnung-PDF-Vorlage', '');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_2_duration']= array('2. Mahnung-Zeitraum', '');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_2_text']= array('2. Mahnung-Text', 'Platzhalter: Herr/Frau = ##gender## , Nachname = ##lastname## , Rechnungssumme = ##brutto## , Rechnungsdatum = ##invoice-date## , Rechnungsnummer = ##invoice-id-str##, Frist-Datum = ##period-date##');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_2_pdf']= array('2. Mahnung-PDF-Vorlage', '');

$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_3_duration']= array('3. Mahnung-Zeitraum', '');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_3_text']= array('3. Mahnung-Text', 'Platzhalter: Herr/Frau = ##gender## , Nachname = ##lastname## , Rechnungssumme = ##brutto## , Rechnungsdatum = ##invoice-date## , Rechnungsnummer = ##invoice-id-str##, Frist-Datum = ##period-date##');
$GLOBALS['TL_LANG']['tl_iao_settings']['iao_reminder_3_pdf']= array('3. Mahnung-PDF-Vorlage', '');
/**
 * Buttons
 */

$GLOBALS['TL_LANG']['tl_iao_settings']['edit']   = 'Einstellung für Rechnungen und Angebote bearbeiten';


$GLOBALS['TL_LANG']['tl_iao_settings']['currency_legend'] = 'Währungs-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['standards_legend'] = 'Standard-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['customermails_legend'] = 'Kunden-Maileinstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['secure_legend'] = 'Sicherheitseinstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['pdf_legend'] = 'PDF-Einstellungen';

$GLOBALS['TL_LANG']['tl_iao_settings']['invoice_legend'] = 'Rechnung-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['offer_legend'] = 'Angebot-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['credit_legend'] = 'Gutschrift-Einstellungen';
$GLOBALS['TL_LANG']['tl_iao_settings']['reminder_legend'] = 'Mahnung-Einstellungen';
?>