<?php
/**
 * TL_ROOT/system/modules/invoice_and_offer/languages/de/tl_member.php
 *
 * Contao extension: invoice_and_offer
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_member']['myid'] = array('Kunden-ID','Falls Datensätze importiert werden, müssen evtl. die Verbindungen zu Rechnnungen,Angebote oder Gutscheinen eine Verknüpfung zum Kundendatensatz haben.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_member']['import_settings'] = 'Import-Einstellungen';
$GLOBALS['TL_LANG']['tl_member']['new']    = array('Neuer Kunde', 'Einen neuen Kunden anlegen');
$GLOBALS['TL_LANG']['tl_member']['title']    = array('Titel', 'z.B. Dr. oder Prof.');
